name: Verify

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: bahmutov/npm-install@v1

      - uses: MansaGroup/nrwl-nx-action@v2.1.0
        with:
          targets: lint,test,build
          parallel: true
